version: '3'

services:
  nginx:
    image: nginx:1.15.12
    environment:
      - "http_proxy=http://172.17.23.19:9090/"
      - "https_proxy=http://172.17.23.19:9090/"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf