version: '3.7'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - code-network
        environment:
            - TZ=Europe/Istanbul
    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
        environment:
            - TZ=Europe/Istanbul

networks:
    code-network:
        driver: bridge
